name = "chinese-japan-translate"
compatibility_date = "2024-01-01"

[build]
command = "cp -r frontend/* . && cp _redirects . || echo 'Build complete'"

[build.environment_variables]
NODE_VERSION = "18"

# Pages 配置
pages_build_output_dir = "."

# 环境变量
[env.production.vars]
DEEPSEEK_API_KEY = "sk-1bde4e88dae04224b43a8ac65e782d51" 