name = "chinese-translate-api"
main = "src/index.js"
compatibility_date = "2023-12-01"

# 环境变量 - 敏感信息通过命令行或UI配置
[vars]
APP_ENV = "production"
VERSION = "2.1"

# KV命名空间配置 - 使用现有的KV
[[kv_namespaces]]
binding = "CACHE"
id = "b29f99f32630402aa8bbecc1182222dc"

[[kv_namespaces]]
binding = "STATS"  
id = "7afc816bfff64a85bc0f09d6892f2a63"

# 开发环境配置
[env.development]
name = "chinese-japanese-translation-dev"
vars = { APP_ENV = "development", VERSION = "2.1-dev" }

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "b29f99f32630402aa8bbecc1182222dc"

[[env.development.kv_namespaces]]
binding = "STATS"
id = "7afc816bfff64a85bc0f09d6892f2a63" 