name = "chinese-japan-translate"
main = "../backend/main.py"
compatibility_date = "2024-01-01"

# Cloudflare Workers Python 配置
[python]
requirements = "../backend/requirements.txt"

# 环境变量 - 在Cloudflare Dashboard中设置
[env.production.vars]
# DEEPSEEK_API_KEY = "你的API密钥"

# 绑定配置
[[env.production.kv_namespaces]]
binding = "TRANSLATE_CACHE"
id = "你的KV存储ID"

# 路由配置
[routes]
pattern = "your-domain.com/*"
zone_name = "your-domain.com" 